/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Calculos.CalcularcosteCarrera;
import Mapas.Simulaciontaxistas;
import Datos.Ubicacion;
import Calculos.CalculosRuta;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.URI;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import Mapas.MapasenNavegador;
import javax.swing.JOptionPane;

/**
 *
 * @author Christian Collaguazo
 */
public class AppMostrarRutas extends javax.swing.JFrame {

    /**
     * Creates new form AppMostrarRutas
     * 
     */
    private int cambiarFondo = -1;
    private CalculosRuta calculos;
    private int cont = 0;
    private CalcularcosteCarrera carrera;
    DefaultListModel model = new DefaultListModel();
    final String poscentral = "-2.899169,-79.004401";
    final Ubicacion ubicacionDefualt = new Ubicacion(poscentral);
    Simulaciontaxistas simulacion = Simulaciontaxistas.getInstance(ubicacionDefualt);
    
    public AppMostrarRutas(CalculosRuta calculos) {
        this.calculos = calculos;
        initComponents();
        if(new File("Movifast_Arch\\fondo.obj").exists()){
            try {
                ObjectInputStream arch = new ObjectInputStream(new FileInputStream("Movifast_Arch\\fondo.obj"));
                Object[] args;
                args = (Object[]) arch.readObject();
                arch.close();
                this.cambiarFondo = (int) args[0];
                if(cambiarFondo == 1)
                {
                    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
                }
                else if (cambiarFondo == 0)
                {
                    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
                }
                
                
            } catch (IOException | ClassNotFoundException ex) {
                System.out.println("Algo paso");
                cambiarFondo = -1;}
        }
        sitioTexto1.setEditable(false);
        sitioTexto2.setEditable(false);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Anterior.doClick();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Anterior = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        listainfo = new javax.swing.JList<>();
        imagenruta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Siguiente = new javax.swing.JButton();
        sitioTexto2 = new javax.swing.JTextField();
        sitioTexto1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonvernavegador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pedirTaxi = new javax.swing.JButton();
        jNombre = new javax.swing.JTextField();
        simulacionPantalla = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1250, 710));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Anterior.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Anterior.setText("Ver Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });
        getContentPane().add(Anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 100, 250, 40));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Tiempo", "Distancia"
            }
        ));
        jScrollPane2.setViewportView(tablaDatos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 850, 160));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        listainfo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        listainfo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listainfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 270, 150));

        imagenruta.setText("jLabel1");
        getContentPane().add(imagenruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 460));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 10, 750));

        Siguiente.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Siguiente.setText("Ver Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 250, 40));
        getContentPane().add(sitioTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 260, 30));

        sitioTexto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitioTexto1ActionPerformed(evt);
            }
        });
        getContentPane().add(sitioTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 260, 30));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lugar De Llegada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 220, 20));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lugar De Salida");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 220, 20));

        botonvernavegador.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        botonvernavegador.setText("Ver en su navegador");
        botonvernavegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonvernavegadorActionPerformed(evt);
            }
        });
        getContentPane().add(botonvernavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 250, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese su Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 150, 30));

        pedirTaxi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        pedirTaxi.setText("Pedir Taxi");
        pedirTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirTaxiActionPerformed(evt);
            }
        });
        getContentPane().add(pedirTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 270, 30));

        jNombre.setText("ingrese aqui");
        jNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNombreMouseClicked(evt);
            }
        });
        jNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 270, 30));

        simulacionPantalla.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        simulacionPantalla.setText("Regresar");
        simulacionPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulacionPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(simulacionPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 470, 270, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoMoviFast2.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 280, 100));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        Fondo.setText("jLabel3");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        // TODO add your handling code here:
        cont--;
        if(cont < 0){
            cont = 0; 
        }
        if(cont == 0){
            Anterior.setEnabled(false);
            Siguiente.setEnabled(true);
        }
        else{
            Siguiente.setEnabled(true);
        }    
        if((calculos.getInformaciondelasUbicaciones().size()-1) == 1)
        {
            Anterior.setEnabled(false);
            Siguiente.setEnabled(false);       
        }
        if(cont >= 0 && cont < calculos.getInformaciondelasUbicaciones().size()-1)
        {
            carrera = new CalcularcosteCarrera(calculos.getTiempos().get(cont), calculos.getKm().get(cont), calculos.getInformaciondelasUbicaciones().get(cont), calculos.getInformaciondelasUbicaciones().get(cont+1));
            carrera.generarCostos();
            model.clear();
            model.addElement("Distancia: " + calculos.getKm().get(cont) + " km");
            model.addElement("Tiempo: " + calculos.getTiempos().get(cont) + " min");
            model.addElement("Valor aproximado del costo");
            model.addElement("del viaje en taxi:");
            model.addElement("Tarifa Diurna: " + carrera.getCarrera().getCostoDiurno());
            model.addElement("Tarifa Noctuna: " + carrera.getCarrera().getCostoNocturno());
            listainfo.setModel(model);
            String[] titulo = new String[3];
            titulo[0] = "Nombre";
            titulo[1] = "Tiempo";
            titulo[2] = "Distancia";
            
            String [][] datosCaminos = new String[calculos.getListaCalles().get(cont).size()][3];
            for (int i = 0; i < datosCaminos.length; i++) {
                datosCaminos[i][0] = calculos.getListaCalles().get(cont).get(i).getNombrecalle();
                datosCaminos[i][1] = calculos.getListaCalles().get(cont).get(i).getTiempo();
                datosCaminos[i][2] = calculos.getListaCalles().get(cont).get(i).getDistancia();

            }
            sitioTexto1.setText(calculos.getInformaciondelasUbicaciones().get(cont).getLugar());
            sitioTexto2.setText(calculos.getInformaciondelasUbicaciones().get(cont+1).getLugar());
             
            TableModel tableModel = new DefaultTableModel(datosCaminos, titulo);
            tablaDatos.setModel(tableModel);
            tablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tablaDatos.setRowSelectionInterval(0, 0);
            Image imagenrut = calculos.getListaImagenesruta().get(cont);
            imagenruta.setIcon(new ImageIcon(imagenrut));
        }
    }//GEN-LAST:event_AnteriorActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        cont++;
        if(cont > calculos.getInformaciondelasUbicaciones().size()-1){
            cont = calculos.getInformaciondelasUbicaciones().size()-2; 
        }
        if(cont == calculos.getInformaciondelasUbicaciones().size()-2){
            Siguiente.setEnabled(false);
            Anterior.setEnabled(true);
        }
        else{
            Anterior.setEnabled(true);
        }    
        
        if(cont >= 0 && cont < (calculos.getInformaciondelasUbicaciones().size()-1))
        {
            
            carrera = new CalcularcosteCarrera(calculos.getTiempos().get(cont), calculos.getKm().get(cont), calculos.getInformaciondelasUbicaciones().get(cont), calculos.getInformaciondelasUbicaciones().get(cont+1));
            carrera.generarCostos();
            model.clear();
            model.addElement("Distancia: " + calculos.getKm().get(cont) + " km");
            model.addElement("Tiempo : " + calculos.getTiempos().get(cont) + " min");
            model.addElement("Valor aproximado del costo");
            model.addElement("del viaje en taxi:");
            model.addElement("Tarifa Diurna: " + carrera.getCarrera().getCostoDiurno());
            model.addElement("Tarifa Noctuna: " + carrera.getCarrera().getCostoNocturno());
            listainfo.setModel(model);
            String[] titulo = new String[3];
            titulo[0] = "Nombre";
            titulo[1] = "Tiempo";
            titulo[2] = "Distancia";

            String [][] datosCaminos = new String[calculos.getListaCalles().get(cont).size()][3];
            for (int i = 0; i < datosCaminos.length; i++) {
                datosCaminos[i][0] = calculos.getListaCalles().get(cont).get(i).getNombrecalle();
                datosCaminos[i][1] = calculos.getListaCalles().get(cont).get(i).getTiempo();
                datosCaminos[i][2] = calculos.getListaCalles().get(cont).get(i).getDistancia();

            }
            sitioTexto1.setText(calculos.getInformaciondelasUbicaciones().get(cont).getLugar());
            sitioTexto2.setText(calculos.getInformaciondelasUbicaciones().get(cont+1).getLugar());
            TableModel tableModel = new DefaultTableModel(datosCaminos, titulo);
            tablaDatos.setModel(tableModel);
            tablaDatos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            tablaDatos.setRowSelectionInterval(0, 0);
            Image imagenrut = calculos.getListaImagenesruta().get(cont);
            imagenruta.setIcon(new ImageIcon(imagenrut));
        }
        
    }//GEN-LAST:event_SiguienteActionPerformed

    private void sitioTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitioTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sitioTexto1ActionPerformed

    private void botonvernavegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonvernavegadorActionPerformed
        // TODO add your handling code here:
        MapasenNavegador nuevo = MapasenNavegador.getInstance();
        nuevo.mostrarImagenNavegador(calculos.getInformaciondelasUbicaciones().get(cont).UbicacionLa_Lo(), calculos.getInformaciondelasUbicaciones().get(cont+1).UbicacionLa_Lo());
        
    }//GEN-LAST:event_botonvernavegadorActionPerformed

    private void pedirTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirTaxiActionPerformed
        // TODO add your handling code here:
        if(jNombre.getText().equals("") == true || jNombre.getText().equals("ingrese aqui")== true)
        {
             JOptionPane.showMessageDialog(null, "Debe ingresar su nombre" , "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            carrera.obtenerTipoTarifa();
            carrera.getCarrera().setNombreUsuario(jNombre.getText());
            carrera.llamaraConductor(cont, calculos , simulacion);
            AppInfoCarrera nuevaCarrera = new AppInfoCarrera(carrera.getCarrera());
            nuevaCarrera.setVisible(true);
            AppInfoCarreraTaxista nuevaCarreraTaxi = new AppInfoCarreraTaxista(carrera.getCarrera());
            nuevaCarreraTaxi.setVisible(true);
        }
        
    }//GEN-LAST:event_pedirTaxiActionPerformed

    private void jNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNombreMouseClicked
        // TODO add your handling code here:
        jNombre.setText("");
    }//GEN-LAST:event_jNombreMouseClicked
    
    private void jNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreActionPerformed

    private void simulacionPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulacionPantallaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_simulacionPantallaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton botonvernavegador;
    private javax.swing.JLabel imagenruta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listainfo;
    private javax.swing.JButton pedirTaxi;
    private javax.swing.JButton simulacionPantalla;
    private javax.swing.JTextField sitioTexto1;
    private javax.swing.JTextField sitioTexto2;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
