/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;



/**
 *
 * @author Christian Collaguazo
 */

public class AppMain extends javax.swing.JFrame {

    /**
     * Creates new form AppMain
     */
    private int cambiarFondo = -1;
    public AppMain() {
        
        initComponents();
        if(new File("Movifast_Arch\\fondo.obj").exists()){
            try {
                ObjectInputStream arch = new ObjectInputStream(new FileInputStream("Movifast_Arch\\fondo.obj"));
                Object[] args;
                args = (Object[]) arch.readObject();
                arch.close();
                this.cambiarFondo = (int) args[0];
                if(cambiarFondo == 1)
                {
                    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_inicio_2.jpg"))); // NOI18N
                }
                else if (cambiarFondo == 0)
                {
                    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_inicio.jpg"))); // NOI18N
                }
                
                
            } catch (IOException | ClassNotFoundException ex) {
                System.out.println("Algo paso");
                cambiarFondo = -1;}
        }
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresoRutas = new javax.swing.JButton();
        mapaTaxista = new javax.swing.JButton();
        CambiarFondo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(890, 540));
        setPreferredSize(new java.awt.Dimension(880, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingresoRutas.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ingresoRutas.setText("Ingreso");
        ingresoRutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoRutasActionPerformed(evt);
            }
        });
        getContentPane().add(ingresoRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 190, 50));

        mapaTaxista.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        mapaTaxista.setText("Mapa Taxistas");
        mapaTaxista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapaTaxistaActionPerformed(evt);
            }
        });
        getContentPane().add(mapaTaxista, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 190, 50));

        CambiarFondo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        CambiarFondo.setText("Fondo");
        CambiarFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarFondoActionPerformed(evt);
            }
        });
        getContentPane().add(CambiarFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 450, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cuenca.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 460, 210));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logoMoviFast3.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 370, 140));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_inicio_2.jpg"))); // NOI18N
        Fondo.setText("jLabel2");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoRutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoRutasActionPerformed
        //Abre la app de ingreso de rutas
        
        AppIngresarRutas apping = new AppIngresarRutas();
        apping.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ingresoRutasActionPerformed

    private void mapaTaxistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapaTaxistaActionPerformed
        // TODO add your handling code here:
        AppMapaTaxista apptaxis = new AppMapaTaxista();
        apptaxis.setVisible(true);
    }//GEN-LAST:event_mapaTaxistaActionPerformed

    private void CambiarFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarFondoActionPerformed
        // TODO add your handling code here:
        if(cambiarFondo == 0 || cambiarFondo == -1)
        {
            Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_inicio_2.jpg"))); // NOI18N
            cambiarFondo = 1;
        }
        else if (cambiarFondo == 1)
        {
            Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_inicio.jpg"))); // NOI18N
            cambiarFondo = 0;
        }
        try {
            
            ObjectOutputStream arch = new ObjectOutputStream(new FileOutputStream("Movifast_Arch\\fondo.obj"));
            Object[] arg = {cambiarFondo};
            arch.writeObject(arg);
            arch.close();
        } 
        catch (IOException ex) {} 
    }//GEN-LAST:event_CambiarFondoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarFondo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton ingresoRutas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton mapaTaxista;
    // End of variables declaration//GEN-END:variables
}
