/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author Christian Collaguazo
 */
import Datos.Ubicacion;
import Mapas.Simulaciontaxistas;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.ImageIcon;
public class AppMapaTaxista extends javax.swing.JFrame {

    /**
     * Creates new form appMapaTaxista
     */
    final String poscentral = "-2.899169,-79.004401";
    final Ubicacion ubicacionDefualt = new Ubicacion(poscentral);
    Simulaciontaxistas simulacion = Simulaciontaxistas.getInstance(ubicacionDefualt);
    private double escalaMovimento = 0.001;
    int zoom = 13;
    private int cambiarFondo = -1;
    public AppMapaTaxista() {
        
        initComponents();
        if(new File("Movifast_Arch\\fondo.obj").exists()){
            try {
                ObjectInputStream arch = new ObjectInputStream(new FileInputStream("Movifast_Arch\\fondo.obj"));
                Object[] args;
                args = (Object[]) arch.readObject();
                arch.close();
                this.cambiarFondo = (int) args[0];
                if(cambiarFondo == 1)
                {
                    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_taxis_2.jpg"))); // NOI18N
                }
                else if (cambiarFondo == 0)
                {
                    Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_taxis_1.jpg"))); // NOI18N
                }
                
                
            } catch (IOException | ClassNotFoundException ex) {
                System.out.println("Algo paso");
                cambiarFondo = -1;}
        }
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        Image imagenTaxis = simulacion.dibujarMapa();
        LabelTaxis.setIcon(new ImageIcon(imagenTaxis));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Arriba1 = new javax.swing.JButton();
        izquierda1 = new javax.swing.JButton();
        derecha1 = new javax.swing.JButton();
        abajo1 = new javax.swing.JButton();
        Plus1 = new javax.swing.JToggleButton();
        menos1 = new javax.swing.JToggleButton();
        LabelTaxis = new javax.swing.JLabel();
        plussesplasamiento = new javax.swing.JButton();
        menordesplazamiento = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(970, 670));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 140, 50));

        Arriba1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Arriba1.setText("Arriba");
        Arriba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arriba1ActionPerformed(evt);
            }
        });
        getContentPane().add(Arriba1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, -1, -1));

        izquierda1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        izquierda1.setText("Izquierda");
        izquierda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izquierda1ActionPerformed(evt);
            }
        });
        getContentPane().add(izquierda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, -1, -1));

        derecha1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        derecha1.setText("Derecha");
        derecha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derecha1ActionPerformed(evt);
            }
        });
        getContentPane().add(derecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, -1, -1));

        abajo1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        abajo1.setText("Abajo");
        abajo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abajo1ActionPerformed(evt);
            }
        });
        getContentPane().add(abajo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, -1));

        Plus1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Plus1.setText("+");
        Plus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plus1ActionPerformed(evt);
            }
        });
        getContentPane().add(Plus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 60, 40));

        menos1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        menos1.setText("-");
        menos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menos1ActionPerformed(evt);
            }
        });
        getContentPane().add(menos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 60, 40));

        LabelTaxis.setText("jLabel1");
        getContentPane().add(LabelTaxis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 640, 640));

        plussesplasamiento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        plussesplasamiento.setText("+");
        plussesplasamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plussesplasamientoActionPerformed(evt);
            }
        });
        getContentPane().add(plussesplasamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 70, -1));

        menordesplazamiento.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        menordesplazamiento.setText("-");
        menordesplazamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menordesplazamientoActionPerformed(evt);
            }
        });
        getContentPane().add(menordesplazamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 70, -1));

        Fondo.setText("jLabel1");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Arriba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arriba1ActionPerformed
        simulacion.setMoverArr();
        LabelTaxis.setIcon(new ImageIcon(simulacion.dibujarMapa()));

    }//GEN-LAST:event_Arriba1ActionPerformed

    private void izquierda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izquierda1ActionPerformed
        simulacion.setMoverIz();
        LabelTaxis.setIcon(new ImageIcon(simulacion.dibujarMapa()));
    }//GEN-LAST:event_izquierda1ActionPerformed

    private void derecha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derecha1ActionPerformed
        simulacion.setMoverDe();
        LabelTaxis.setIcon(new ImageIcon(simulacion.dibujarMapa()));
    }//GEN-LAST:event_derecha1ActionPerformed

    private void abajo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abajo1ActionPerformed
        simulacion.setMoverAba();
        LabelTaxis.setIcon(new ImageIcon(simulacion.dibujarMapa()));
    }//GEN-LAST:event_abajo1ActionPerformed

    private void Plus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plus1ActionPerformed

        simulacion.acercarMapa();
        LabelTaxis.setIcon(new ImageIcon(simulacion.dibujarMapa()));

    }//GEN-LAST:event_Plus1ActionPerformed

    private void menos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menos1ActionPerformed
        // TODO add your handling code here:
        simulacion.alejarMapa();
        LabelTaxis.setIcon(new ImageIcon(simulacion.dibujarMapa()));
    }//GEN-LAST:event_menos1ActionPerformed

    private void plussesplasamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plussesplasamientoActionPerformed
        // TODO add your handling code here:
        escalaMovimento += 0.001;
        simulacion.setEscalamovimiento(escalaMovimento);
    }//GEN-LAST:event_plussesplasamientoActionPerformed

    private void menordesplazamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menordesplazamientoActionPerformed
        // TODO add your handling code here:
        escalaMovimento-= 0.001;
        escalaMovimento = (escalaMovimento < 0.0000) ? 0.001 : escalaMovimento ;
        simulacion.setEscalamovimiento(escalaMovimento);

    }//GEN-LAST:event_menordesplazamientoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arriba1;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LabelTaxis;
    private javax.swing.JToggleButton Plus1;
    private javax.swing.JButton abajo1;
    private javax.swing.JButton derecha1;
    private javax.swing.JButton izquierda1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton menordesplazamiento;
    private javax.swing.JToggleButton menos1;
    private javax.swing.JButton plussesplasamiento;
    // End of variables declaration//GEN-END:variables
}
